SKILL_JUPITER		<-239
STATE_JUPITER		<-239

CUSTOM_ANI_JUPITER_CAST		<-130
CUSTOM_ANI_JUPITER_PICKUP		<-131
CUSTOM_ANI_JUPITER_CATCH		<-132
CUSTOM_ANI_JUPITER_ATTACK_A		<-133
CUSTOM_ANI_JUPITER_ATTACK_B		<-134
CUSTOM_ANI_JUPITER_ATTACK_C		<-135
CUSTOM_ANI_JUPITER_ATTACK_DASH		<-136
CUSTOM_ANI_JUPITER_ATTACK_JUMP		<-137
CUSTOM_ANI_JUPITER_ATTACK_UPPER		<-138
CUSTOM_ANI_JUPITER_ATTACK_QUAKEAREA		<-139

CUSTOM_ATK_JUPITER_ATTACK_A		<-98
CUSTOM_ATK_JUPITER_ATTACK_B		<-99
CUSTOM_ATK_JUPITER_ATTACK_C		<-100
CUSTOM_ATK_JUPITER_ATTACK_JUMP		<-101

