





STATE_SWORDMAIN <- 230

STATE_HARDATTACK_0 <- 235
STATE_HARDATTACK_HELL <- 236
STATE_GHOSTOUT <- 237



SKILL_HARDATTACK_0    <- 246
SKILL_HARDATTACK_HELL <- 247
SKILL_GHOSTOUT        <- 250

SKILL_SWORDMAIN <- 245


CUSTOM_ANI_HARDATTACK_READY <- 159
CUSTOM_ANI_HARDATTACK_ATTACK <- 160
CUSTOM_ANI_HARDATTACK_HELL_BOBY <- 161

CUSTOM_ANI_GHOSTOUT_CASTING <- 162
CUSTOM_ANI_GHOSTOUT_JUMP <- 163
CUSTOM_ANI_GHOSTOUT_ATTACK <- 164
CUSTOM_ANI_SWORDMAIN_BOBY <- 165



ATTACKINFO_HARDATTACK_HELL <- 91

